# Generated by Django 4.2.30 on 2026-05-25 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=160)),
                ('sesiones_semanales', models.PositiveSmallIntegerField(default=2)),
                ('horas_por_sesion', models.PositiveSmallIntegerField(default=2)),
                ('es_transversal', models.BooleanField(default=False)),
                ('codigo_global_compartido', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['curso__titulacion__nombre', 'curso__numero', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('capacidad', models.PositiveIntegerField(default=30)),
                ('recursos', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['titulacion__nombre', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='FranjaHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('dia', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIÉRCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('etiqueta', models.CharField(blank=True, max_length=50)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'franja horaria',
                'verbose_name_plural': 'franjas horarias',
                'ordering': ['dia', 'hora_inicio'],
                'unique_together': {('dia', 'hora_inicio', 'hora_fin')},
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('tipo', models.CharField(choices=[('TEORIA', 'Teoría'), ('PRACTICAS', 'Prácticas'), ('LAB', 'Laboratorio')], default='TEORIA', max_length=20)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='horarios.curso')),
            ],
            options={
                'ordering': ['curso__numero', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('anio_academico', models.CharField(default='2025-2026', max_length=20)),
                ('semestre', models.CharField(choices=[('1', 'Primer semestre'), ('2', 'Segundo semestre')], max_length=1)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_aprobados', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.curso')),
            ],
            options={
                'ordering': ['anio_academico', 'semestre', 'titulacion__nombre', 'curso__numero'],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('area_conocimiento', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'profesores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Titulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('codigo', models.SlugField(max_length=30, unique=True)),
                ('duracion_anios', models.PositiveSmallIntegerField(default=4)),
                ('permite_manana_tarde', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'titulación',
                'verbose_name_plural': 'titulaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('observaciones', models.CharField(blank=True, max_length=250)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='horarios.asignatura')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='horarios.aula')),
                ('franja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='horarios.franjahoraria')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='horarios.grupo')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='horarios.horario')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='horarios.profesor')),
            ],
            options={
                'verbose_name': 'sesión',
                'verbose_name_plural': 'sesiones',
                'ordering': ['franja__dia', 'franja__hora_inicio', 'grupo__nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('asignaturas', models.ManyToManyField(blank=True, related_name='alumnos', to='horarios.asignatura')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horarios.grupo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de alumno',
                'verbose_name_plural': 'perfiles de alumnos',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nivel', models.CharField(choices=[('INFO', 'Informativa'), ('SUCCESS', 'Éxito'), ('WARNING', 'Advertencia'), ('ERROR', 'Error')], default='INFO', max_length=20)),
                ('titulo', models.CharField(max_length=120)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('url_destino', models.CharField(blank=True, max_length=300)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.AddField(
            model_name='horario',
            name='titulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.titulacion'),
        ),
        migrations.CreateModel(
            name='DisponibilidadProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('PREFERENTE', 'Disponibilidad preferente'), ('DISPONIBLE', 'Disponible'), ('BLOQUEADO', 'Indisponible')], default='DISPONIBLE', max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('franja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.franjahoraria')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='horarios.profesor')),
            ],
            options={
                'verbose_name': 'disponibilidad de profesor',
                'verbose_name_plural': 'disponibilidades de profesores',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='titulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='horarios.titulacion'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Borrado'), ('WORKFLOW', 'Cambio de estado'), ('LOGIN', 'Acceso'), ('VALIDATION', 'Validación')], max_length=20)),
                ('modelo', models.CharField(max_length=80)),
                ('objeto_id', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.TextField()),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_nuevo', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ['-creado'],
            },
        ),
        migrations.AddField(
            model_name='asignatura',
            name='aula_preferente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horarios.aula'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='horarios.curso'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='profesor_titular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas', to='horarios.profesor'),
        ),
        migrations.AddConstraint(
            model_name='sesion',
            constraint=models.UniqueConstraint(fields=('horario', 'grupo', 'franja'), name='uq_sesion_grupo_franja_en_horario'),
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('anio_academico', 'semestre', 'titulacion', 'curso')},
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidadprofesor',
            unique_together={('profesor', 'franja')},
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('titulacion', 'numero')},
        ),
    ]
