# Generated by Django 4.2.30 on 2026-05-27 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('PREFERENTE', 'Disponibilidad preferente'), ('DISPONIBLE', 'Disponible'), ('BLOQUEADO', 'Indisponible')], max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'historial de disponibilidad',
                'verbose_name_plural': 'historial de disponibilidades',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ProfesorSuplente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('area_conocimiento', models.CharField(max_length=120)),
                ('prioridad', models.PositiveSmallIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'profesor suplente',
                'verbose_name_plural': 'profesores suplentes',
                'ordering': ['asignatura__nombre', 'prioridad', 'profesor__nombre'],
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='accion',
            field=models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Borrado'), ('WORKFLOW', 'Cambio de estado'), ('LOGIN', 'Acceso'), ('VALIDATION', 'Validación'), ('REPORT', 'Informe'), ('GENERATION', 'Generación')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='sesion',
            constraint=models.UniqueConstraint(fields=('horario', 'asignatura', 'grupo', 'franja'), name='uq_sesion_asignatura_grupo_franja'),
        ),
        migrations.AddField(
            model_name='profesorsuplente',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suplentes', to='horarios.asignatura'),
        ),
        migrations.AddField(
            model_name='profesorsuplente',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suplencias', to='horarios.profesor'),
        ),
        migrations.AddField(
            model_name='historialdisponibilidad',
            name='franja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.franjahoraria'),
        ),
        migrations.AddField(
            model_name='historialdisponibilidad',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_disponibilidad', to='horarios.profesor'),
        ),
        migrations.AddField(
            model_name='historialdisponibilidad',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='profesorsuplente',
            unique_together={('asignatura', 'profesor')},
        ),
    ]
